#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
if [ -d "$SCRIPT_DIR/venv" ]; then
    source "$SCRIPT_DIR/venv/bin/activate"
else
    source "$SCRIPT_DIR/../venv/bin/activate"
fi
python "$SCRIPT_DIR/oochat.py" "$@"
